Repository minibeit/git-study, pull requests merged in 2021-07, with the labels that each got.

#2 [BE] 테스트 이슈 예시
  branch.md
  hello.txt
Labels: Backend

#5 [BE] 테스트 이슈2
  hello.txt
  test.md
Labels: Asking for Review, Backend

#7 [FE] 이슈 테스트3
  hello.txt
  hi.txt
Labels: Asking for Review, frontend
